services:
  - type: web
    name: cricvision-ai
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000